# Generated by Django 3.1.7 on 2021-07-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbBoard',
            fields=[
                ('board_name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('board_production_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'TB_board',
            },
        ),
        migrations.CreateModel(
            name='TbMember',
            fields=[
                ('m_email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64, null=True)),
                ('m_name', models.CharField(max_length=12)),
                ('m_rg_no', models.IntegerField(blank=True, null=True)),
                ('class_no', models.IntegerField()),
                ('department', models.CharField(max_length=15)),
                ('m_image', models.CharField(blank=True, max_length=45, null=True)),
                ('m_introduce', models.CharField(blank=True, max_length=60, null=True)),
                ('sysop_status', models.IntegerField()),
            ],
            options={
                'db_table': 'TB_member',
            },
        ),
        migrations.CreateModel(
            name='TbPost',
            fields=[
                ('post_seq', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.CharField(max_length=9000)),
                ('post_image', models.CharField(blank=True, max_length=45, null=True)),
                ('post_rg_dt', models.DateTimeField()),
                ('post_likes_count', models.IntegerField()),
                ('post_visits_count', models.IntegerField()),
                ('board_name', models.ForeignKey(db_column='board_name', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbboard')),
                ('parent_post_seq', models.ForeignKey(blank=True, db_column='parent_post_seq', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbpost')),
                ('post_writer', models.ForeignKey(blank=True, db_column='post_writer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_post',
            },
        ),
        migrations.CreateModel(
            name='TbProject',
            fields=[
                ('p_seq', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=45)),
                ('p_rg_dt', models.DateTimeField()),
                ('maximum_m', models.IntegerField(blank=True, null=True)),
                ('producer_hidden', models.IntegerField()),
                ('p_image', models.CharField(blank=True, max_length=45, null=True)),
                ('p_rg_no', models.IntegerField()),
                ('p_recruit_status', models.IntegerField()),
                ('p_producer', models.ForeignKey(db_column='p_producer', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_project',
            },
        ),
        migrations.CreateModel(
            name='TbProjectProgress',
            fields=[
                ('p_seq', models.OneToOneField(db_column='p_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbproject')),
                ('progress_date', models.DateField()),
                ('progress_content', models.CharField(max_length=6000)),
                ('homework', models.CharField(blank=True, max_length=100, null=True)),
                ('progress_image', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'TB_project_progress',
                'unique_together': {('p_seq', 'progress_date')},
            },
        ),
        migrations.CreateModel(
            name='TbTag',
            fields=[
                ('tag_name', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('tag_production_dt', models.DateTimeField()),
                ('producer', models.ForeignKey(db_column='producer', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_tag',
            },
        ),
        migrations.CreateModel(
            name='TbFormQuestion',
            fields=[
                ('question_seq', models.AutoField(primary_key=True, serialize=False)),
                ('question_content', models.CharField(max_length=100)),
                ('producer_dt', models.DateTimeField()),
                ('question_producer', models.ForeignKey(db_column='question_producer', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_form_question',
            },
        ),
        migrations.CreateModel(
            name='TbFormAnswer',
            fields=[
                ('form_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('question_seq', models.IntegerField()),
                ('form_writer', models.CharField(max_length=40)),
                ('answer_content', models.CharField(max_length=6000)),
            ],
            options={
                'db_table': 'TB_form_answer',
                'unique_together': {('form_seq', 'question_seq', 'form_writer')},
            },
        ),
        migrations.CreateModel(
            name='TbForm',
            fields=[
                ('form_seq', models.AutoField(primary_key=True, serialize=False)),
                ('form_title', models.CharField(max_length=45)),
                ('form_introduce', models.CharField(blank=True, max_length=1500, null=True)),
                ('form_start_dt', models.DateTimeField()),
                ('form_end_dt', models.DateTimeField()),
                ('rg_no', models.IntegerField(blank=True, null=True)),
                ('producer', models.ForeignKey(db_column='producer', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_form',
            },
        ),
        migrations.CreateModel(
            name='TbComment',
            fields=[
                ('comment_seq', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=3000)),
                ('comment_likes_count', models.IntegerField()),
                ('comment_rg_dt', models.DateTimeField()),
                ('comment_writer', models.ForeignKey(db_column='comment_writer', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
                ('post_seq', models.ForeignKey(db_column='post_seq', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbpost')),
            ],
            options={
                'db_table': 'TB_comment',
            },
        ),
        migrations.CreateModel(
            name='TbBook',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=45)),
                ('book_rg_dt', models.DateTimeField()),
                ('book_borrower', models.ForeignKey(blank=True, db_column='book_borrower', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
                ('book_owner', models.ForeignKey(db_column='book_owner', on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_owner', to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_book',
                'unique_together': {('isbn', 'book_owner')},
            },
        ),
        migrations.AddField(
            model_name='tbboard',
            name='board_producer',
            field=models.ForeignKey(db_column='board_producer', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember'),
        ),
        migrations.CreateModel(
            name='TbProjectPlan',
            fields=[
                ('p_seq', models.OneToOneField(db_column='p_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbproject')),
                ('plan_date', models.DateField()),
                ('plan_content', models.CharField(max_length=100)),
                ('homework', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TB_project_plan',
                'unique_together': {('p_seq', 'plan_date')},
            },
        ),
        migrations.CreateModel(
            name='TbProjectMember',
            fields=[
                ('p_seq', models.OneToOneField(db_column='p_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbproject')),
                ('m_role', models.CharField(blank=True, max_length=30, null=True)),
                ('sign_up_dt', models.DateTimeField()),
                ('sign_up_status', models.IntegerField()),
                ('p_m', models.ForeignKey(db_column='p_m', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_project_member',
                'unique_together': {('p_seq', 'p_m')},
            },
        ),
        migrations.CreateModel(
            name='TbProjectTag',
            fields=[
                ('p_seq', models.OneToOneField(db_column='p_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbproject')),
                ('tag_name', models.ForeignKey(db_column='tag_name', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbtag')),
            ],
            options={
                'db_table': 'TB_project_tag',
                'unique_together': {('p_seq', 'tag_name')},
            },
        ),
        migrations.CreateModel(
            name='TbPostTag',
            fields=[
                ('post_seq', models.OneToOneField(db_column='post_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbpost')),
                ('tag_name', models.ForeignKey(db_column='tag_name', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbtag')),
            ],
            options={
                'db_table': 'TB_post_tag',
                'unique_together': {('post_seq', 'tag_name')},
            },
        ),
        migrations.CreateModel(
            name='TbMemberTag',
            fields=[
                ('m_email', models.OneToOneField(db_column='m_email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbmember')),
                ('tag_name', models.ForeignKey(db_column='tag_name', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbtag')),
            ],
            options={
                'db_table': 'TB_member_tag',
                'unique_together': {('m_email', 'tag_name')},
            },
        ),
        migrations.CreateModel(
            name='TbFormContent',
            fields=[
                ('form_seq', models.OneToOneField(db_column='form_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbform')),
                ('question_seq', models.ForeignKey(db_column='question_seq', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbformquestion')),
            ],
            options={
                'db_table': 'TB_form_content',
                'unique_together': {('form_seq', 'question_seq')},
            },
        ),
        migrations.CreateModel(
            name='TbBookTag',
            fields=[
                ('isbn', models.OneToOneField(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbbook')),
                ('book_owner', models.ForeignKey(db_column='book_owner', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_book_owner', to='cbums.tbbook')),
                ('tag_name', models.ForeignKey(db_column='tag_name', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbtag')),
            ],
            options={
                'db_table': 'TB_book_tag',
                'unique_together': {('isbn', 'book_owner', 'tag_name')},
            },
        ),
        migrations.CreateModel(
            name='TbBoardSubscription',
            fields=[
                ('board_name', models.OneToOneField(db_column='board_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbboard')),
                ('subscription_dt', models.DateTimeField()),
                ('subscriber', models.ForeignKey(db_column='subscriber', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbmember')),
            ],
            options={
                'db_table': 'TB_board_subscription',
                'unique_together': {('board_name', 'subscriber')},
            },
        ),
        migrations.CreateModel(
            name='TbProjectParticipation',
            fields=[
                ('p_seq', models.OneToOneField(db_column='p_seq', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cbums.tbprojectprogress')),
                ('attend_status', models.IntegerField()),
                ('homework_submit_status', models.IntegerField(blank=True, null=True)),
                ('p_m', models.ForeignKey(db_column='p_m', on_delete=django.db.models.deletion.DO_NOTHING, to='cbums.tbprojectmember')),
                ('progress_date', models.ForeignKey(db_column='progress_date', on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_progress_date', to='cbums.tbprojectprogress')),
            ],
            options={
                'db_table': 'TB_project_participation',
                'unique_together': {('p_seq', 'progress_date', 'p_m')},
            },
        ),
    ]
